# Generated by Django 2.1.7 on 2019-03-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20190321_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='userprofile/profile_image/'),
        ),
    ]
